namespace BE_project.DTOs.Record
{
    public class CreateRecordDTO
    {
        //id generated by DB
        public int UserIdId { get; set; }
        public int CategoryId { get; set; }
        public DateTime CreatedDate { get; set; }
        public decimal Amount { get; set; }
    }
}
