namespace BE_project.DTOs.Record
{
    public class CreateRecordDTO
    {
        //id generated by DB
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public decimal Amount { get; set; }
    }
}
